development:
  address: "smtp.gmail.com"
  port: 587
  domain: "innodealing"
  authentication: "plain"
  user_name: #ENV['GMAIL_SMTP_USER']
  password: #ENV['GMAIL_SMTP_PASSWORD']
  enable_starttls_auto: true
production:
  address: "smtp.gmail.com"
  port: 587
  domain: "innodealing"
  authentication: "plain"
  user_name: #ENV['GMAIL_SMTP_USER']
  password: #ENV['GMAIL_SMTP_PASSWORD']
  enable_starttls_auto: true
